a = input("Digite algo: ")
print("O tipó primitivo é: ", type(a))
print("Só tem espaço?", a.isspace())
print("É um numero?: ", a.isnumeric())
print("É alfabetico? ", a.isalpha())
print("É alfanumerico? ", a.isalnum())
print("Esta em minusculo?", a.isupper())
print("Esta em maiusculo?", a.isupper())
print("Está captalizada?", a.istitle())